export const expertise = [
	{ label: "Algorithm design", value: "Algorithm design" },
	{ label: "Algorithms", value: "Algorithms" },
	{ label: "Artificial intelligence", value: "Artificial intelligence" },
	{ label: "Automata theory", value: "Automata theory" },
	{ label: "Automated reasoning", value: "Automated reasoning" },
	{ label: "Bioinformatics", value: "Bioinformatics" },
	{ label: "Cloud computing", value: "Cloud computing" },
	{ label: "Coding theory", value: "Coding theory" },
	{ label: "Compiler theory", value: "Compiler theory" },
	{ label: "Computability theory", value: "Computability theory" },
	{ label: "Computational chemistry", value: "Computational chemistry" },
	{ label: "Computational complexity theory", value: "Computational complexity theory" },
	{ label: "Computational physics", value: "Computational physics" },
	{ label: "Computational science", value: "Computational science" },
	{ label: "Computer architecture", value: "Computer architecture" },
	{ label: "Computer graphics", value: "Computer graphics" },
	{ label: "Computer programming", value: "Computer programming" },
	{ label: "Computer security", value: "Computer security" },
	{ label: "Computer vision", value: "Computer vision" },
	{ label: "Concurrency", value: "Concurrency" },
	{ label: "Cryptography", value: "Cryptography" },
	{ label: "Data mining", value: "Data mining" },
	{ label: "Data science", value: "Data science" },
	{ label: "Data structures", value: "Data structures" },
	{ label: "Discrete Mathematics", value: "Discrete Mathematics" },
	{ label: "Distributed computing", value: "Distributed computing" },
	{ label: "Evolutionary computing", value: "Evolutionary computing" },
	{ label: "Formal methods", value: "Formal methods" },
	{ label: "Formal semantics", value: "Formal semantics" },
	{ label: "Game theory", value: "Game theory" },
	{ label: "Graph theory", value: "Graph theory" },
	{ label: "Human–computer interaction", value: "Human–computer interaction" },
	{ label: "Image processing", value: "Image processing" },
	{ label: "Information visualization", value: "Information visualization" },
	{ label: "Machine learning", value: "Machine learning" },
	{ label: "Mathematical logic", value: "Mathematical logic" },
	{ label: "Mobile computing", value: "Mobile computing"},
	{ label: "Natural language processing", value: "Natural language processing" },
	{ label: "Networking", value: "Networking" },
	{ label: "Number theory", value: "Number theory" },
	{ label: "Numerical analysis", value: "Numerical analysis" },
	{ label: "Operating systems", value: "Operating systems" },
	{ label: "Parallel computing", value: "Parallel computing" },
	{ label: "Programming language theory", value: "Programming language theory" },
	{ label: "Quantum computing", value: "Quantum computing" },
	{ label: "Relational databases", value: "Relational databases" },
	{ label: "Reverse engineering", value: "Reverse engineering" },
	{ label: "Robotics", value: "Robotics" },
	{ label: "Soft computing", value: "Soft computing" },
	{ label: "Software engineering", value: "Software engineering" },
	{ label: "Structured Storage", value: "Structured Storage" },
	{ label: "Symbolic computation", value: "Symbolic computation" },
	{ label: "Type theory", value: "Type theory" },
	{ label: "Web development", value: "Web development" }
];
